### ISSUE TITLE
Support for large messages

### ISSUE THREAD

**Issue by yoogx** [OpenAADL/polyorb-hi-ada#5]
In its current implementation, PolyORB-HI/Ada is limited to packed of size < 64KiB. This should be changed to 4GiB

**Comment by maxime-esa** [comment]
In taste there are two places that relate to this limitation:
the `DataView.aadl` files (generated by `DMT`) contain: 

```
DATA IMPLEMENTATION HugeMsg_Buffer.impl
    -- Buffer to hold a marshalled data of type HugeMsg
SUBCOMPONENTS
    Buffer : data HugeMsg_Buffer_Max.impl;
    Length : data Base_Types::Unsigned_16;
PROPERTIES
```  

And the wrapper code in Ada (generated by `buildsupport` has a hardcoded use of `Unsigned_16`:

```
Value.OUTPORT_image_DATA.Length := PolyORB_HI_Generated.Types.Unsigned_16 (IN_nice_picture_size);
```

Let me know if/when we should change these.

**Comment by yoogx** [comment]
Solution on your end is to change Length to be Unsigned_32, I'll handle the other parts in the runtime

**Comment by maxime-esa** [comment]
Ok the changes are committed on DMT and buildsupport sides

**Comment by yoogx** [comment]
Implementation of this ticket move to openaadl/ocarina#99
