### ISSUE TITLE
pragma Restriction in gnat.adc

### ISSUE THREAD

**Issue by maxime-esa** [OpenAADL/polyorb-hi-ada#7]
On native platforms there is a `pragma Restrictions (No_Streams)` specified in `gnat.adc`. However, the serial driver for native platforms (`polyorb_hi_drivers_native_uart.adb`) - as well as other serial drivers - include and use Ada.Streams. Because of this, the native builds that use serial drivers fail.

**Comment by yoogx** [comment]
Closed, will be handled as openaadl/ocarina#118
